---
- name: Gather version information from Cisco IOS XR devices
  gather_facts: no
  hosts: GT-XR-UFINET
  connection: network_cli
  tasks:
    - name: Run show version brief
      ios_command:
        commands:
          - show version
      register: show_version_output

    - name: Display show version brief output
      debug:
        msg: "{{ show_version_output.stdout }}"
