---
- name: Run show version command
  hosts: GT-XR-UFINET
  gather_facts: no
  tasks:
    - name: Run show version command
      ios_command:
        commands:
          - show version
      register: version_output

    - name: Print show version output
      debug:
        msg: "{{ version_output.stdout }}"
